### ISSUE TITLE
Replace QR Code API

### ISSUE THREAD

**Issue by jessienab** [corbindavenport/imageshare#18]
To reduce issues relating to user privacy, it would be ideal to add support or implement the use of a self-hosted/local piece of code, to generate QR codes of image URLs.

PHPQRCode seems to be a viable [PHP based project](https://phpqrcode.sourceforge.net/) for this kind of work, however I imagine it stores the image locally. I guess a solution to that would be exporting the generated image as a set of base64 text the browser would present? Can the 3DS Browser even accept that kind of data?

There are some other QR generating alternatives, but I haven't found one (in a quick search) that doesn't require payment or an account on someone's end.

Thank you for the code and service!

**Comment by corbindavenport** [comment]
ImageShare now uses the [goQR.me API](https://goqr.me/api/) for rendering QR codes, since the Google API appears to be shut down (it has been marked as deprecated for a while) and goQR supports both HTTP and HTTPS connections. Ideally ImageShare still needs to move to a local solution for QR code generation.

**Comment by corbindavenport** [comment]
Merged this into #28.
