### ISSUE TITLE
Improve 3DS game handling

### ISSUE THREAD

**Issue by corbindavenport** [corbindavenport/imageshare#25]
Animal Crossing screenshots don't work after #22 was merged. It might also make sense to move the game lists out of the code repository, or at least make it easily synchronized with the original source.

**Comment by spaghefoo** [comment]
could you give me an animal crossing jpg screenshot from a 3ds? i don't have the game to test this one...

**Comment by corbindavenport** [comment]
The sample image in the repo has the metadata: https://github.com/corbindavenport/imageshare/blob/main/sample.jpg

**Comment by spaghefoo** [comment]
After checking yesterday, the titleID associated with the image was actually pointing on an update. We didn't check for updates titleIDs(which have a distinct titleID pattern) because when writing the code i thought "we don't need to check for game updates it's only games we are interested in.". It seems like animal crossing proved me wrong somehow. now it works for animal crossing, however it shows as "Animal Crossing™: New Leaf Update Ver. 1.5".
I also encounted an other(small) issue where when uploading some game images(Pokémon sun for example) it would show as <Game Title>: Update. I modifed the code a bit to fix that.
I'll check for the json repo thing at a later date but the main issue is fixed now.

**Comment by corbindavenport** [comment]
Closing this as the improved 3DS game title detection is now in the Node.js rewrite (#28). In the future there might be a mechanism to update the title database, but there aren't any new games being made for the 3DS or Wii U, so that's not a big deal for now.
